#!/usr/bin/env python3

from PIL import Image
from PIL.ExifTags import TAGS
import sys
import os
import time

def print_picdata(image_path):
    try:
        file_stats = os.stat(image_path)
        file_size = file_stats.st_size
        creation_time = time.ctime(file_stats.st_ctime)
        modification_time = time.ctime(file_stats.st_mtime)
        access_time = time.ctime(file_stats.st_atime)

        print(f"\nOS Data for {image_path}:\n")
        print(f"File Size: {file_size} bytes")
        print(f"Creation Time: {creation_time}")
        print(f"Last Modification Time: {modification_time}")
        print(f"Last Access Time: {access_time}\n")

        image = Image.open(image_path)
        exif_data = image._getexif()
        if exif_data is not None:
            print(f"\nEXIF Metadata for {image_path}:\n")
            for tag, value in exif_data.items():
                tag_name = TAGS.get(tag, tag)
                print(f"{tag_name}: {value}")
        else:
            print(f"\nNo EXIF metadata found for {image_path}")
        print("--------------------")

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    for image_path in sys.argv[1:]:
        if image_path.endswith(('.jpg', '.jpeg', '.png', '.gif', '.bmp')):
            print_picdata(image_path)
        else:
            print(f"{os.path.basename(image_path)}: file extension not accepted")
